export {default as Home} from './Home'
export {default as Favorites} from './Favorites'
export {default as Edit} from './Edit'
export {default as Detail} from './Detail'
export {default as Search} from './Search'